from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ToolProvider(Protocol):
    def list_dir(self, path: str | None = None) -> str: ...

    def read_file(self, path: str) -> str: ...

    def write_file(self, path: str, content: str) -> str: ...

    def run_command(self, command: str, cwd: str | None = None) -> str: ...

    def apply_patch(self, path: str, search: str, replace: str, replace_all: bool = False) -> str: ...

    def file_search(self, pattern: str, max_results: int = 100) -> str: ...

    def grep_search(
        self,
        query: str,
        include_pattern: str | None = None,
        is_regexp: bool = False,
        max_results: int = 100,
    ) -> str: ...

    def list_code_usages(self, symbol: str, include_pattern: str | None = None, max_results: int = 100) -> str: ...

    def get_changed_files(self) -> str: ...

    def start_background_command(self, command: str, cwd: str | None = None) -> str: ...

    def get_background_output(self, job_id: str, tail_lines: int = 200) -> str: ...

    def kill_background_process(self, job_id: str) -> str: ...

    async def web_fetch(self, url: str, max_chars: int = 12000) -> str: ...
