"""SEC (OE-07): Server-side session-ID management and validation.

Prevents session hijacking by ensuring clients cannot specify arbitrary session IDs.
Uses HMAC signature to bind session IDs to their originating connection.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import re
import secrets
import time

# Signing key — generated once per server process lifetime.
# In production, this should come from a persistent secret store.
_raw_signing_key = os.getenv("SESSION_SIGNING_KEY", "").encode("utf-8")
if _raw_signing_key:
    _SESSION_SIGNING_KEY: bytes = _raw_signing_key
else:
    # SEC (CRYPTO-02): Warn about ephemeral session signing key
    import logging as _logging

    _logging.getLogger(__name__).warning(
        "SESSION_SIGNING_KEY not set — using ephemeral key. "
        "Sessions will be invalidated on restart. "
        "Set SESSION_SIGNING_KEY in .env for persistent sessions."
    )
    _app_env = os.getenv("APP_ENV", "development").strip().lower()
    if _app_env == "production":
        raise RuntimeError(
            "SESSION_SIGNING_KEY is required in production mode but not set. "
            "Set SESSION_SIGNING_KEY in .env for persistent sessions."
        )
    _SESSION_SIGNING_KEY = secrets.token_bytes(32)


def generate_session_id(connection_id: str) -> str:
    """Generate a signed session ID bound to a connection.

    Format: ``{connection_id}.{timestamp}.{signature}``
    """
    timestamp = str(int(time.time()))
    payload = f"{connection_id}.{timestamp}"
    signature = _sign(payload)
    return f"{payload}.{signature}"


def validate_session_id(session_id: str, connection_id: str) -> bool:
    """Validate that a session ID was generated by this server for this connection.

    Returns True if the session ID is valid and bound to the given connection.
    """
    parts = session_id.split(".")
    if len(parts) != 3:
        return False

    claimed_connection, timestamp_str, signature = parts

    # Verify the session belongs to this connection
    if claimed_connection != connection_id:
        return False

    # Verify HMAC signature
    payload = f"{claimed_connection}.{timestamp_str}"
    expected_signature = _sign(payload)
    return hmac.compare_digest(signature, expected_signature)


def validate_session_id_format(session_id: str) -> bool:
    """Quick format validation for session IDs.

    Checks length and character constraints without cryptographic verification.
    """
    if not session_id or len(session_id) > 256:
        return False
    # Allow UUID-style, signed-style, and simple alphanumeric IDs
    return bool(re.fullmatch(r"[A-Za-z0-9._\-]+", session_id))


def _sign(payload: str) -> str:
    """Create HMAC-SHA256 signature for a payload."""
    # SEC (CRYPTO-06): Use full 64-char hex digest instead of truncated 16-char
    # for stronger collision resistance (256-bit vs 64-bit).
    return hmac.new(
        _SESSION_SIGNING_KEY,
        payload.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
